name: Backend CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          cd backend
          npm install
          
      - name: Run Tests (Optional)
        run: |
          cd backend
          npm test  # Optional step if you have test scripts

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/wow-app/backend
            git pull origin main
            npm install
            pm2 restart server.js  # Restart the backend app with PM2
